name: .NET Build App
on:
  push:
    branches: [ "master" ]
env:
 dev: Server=(localdb)\\\\mssqllocaldb;Database=applicationdb;Trusted_Connection=True;
 prod: ${{ secrets.CONNECTION }}
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .NET version 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Replace connection string 
      run: sed -i 's|${{ env.dev }}|${{ env.prod }}|g' ESP/appsettings.json
    - name: Removing appsettings
      run : rm -rf ESP/appsettings*.json
    - name: Publish
      run : dotnet publish -c Release --no-build --output ./publish/ESP ./ESP/ESP.csproj
    - name: Delete webconfig
      run : rm -rf ./publish/ESP/web.config
    - name: Upload dotnet artifacts
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: ./publish
    - name: Download dotnet artifacts
      uses: actions/download-artifact@v3
      with:
        path: publish
      
